### ISSUE TITLE
Estoy de vuelta!!! Cosas que arreglar

### ISSUE THREAD

**Issue by anddonram** [Metronus/metronus#1]
Qué tal, señores de Metronus? Me echabais de menos? Regreso a este espacio en la segunda temporada de GitHub Issues, para dar por saco un poco más.
Aquí, haciendo pruebas de acceso y tal, y me encuento estas cosas:

-Metrobus en la página inicial?? Somos MetroNus!!!
-La lista de proyectos peta, en concreto líneas 14 y 15. href="{% url 'project_edit' project.id %}" esta mal escrito, o no lo reconoce. La lista de departamentos va bien y usa otro código, copiaos de ese
-En la lista, los formularios no traducen las cabeceras, de hecho salen los códigos de los mensajes a traducir . Para muestra un botón.
![image](https://cloud.githubusercontent.com/assets/22744247/23761458/27724662-04f3-11e7-9cc0-4757c439321d.png)
-En general, vendría bien un menú simple con los enlaces, aunque sean todos, para no tener que ir escribiendo la url.
Sin más, yo me ofrezco a meter las narices para arreglar algunas cosillas, pero quiero que me den permisos.

Saludos y que sea leve, colleagues!!!

PD: qué tal estaría un sistema de gestión de incidencias a lo EGC? aunque nadie nos obliga.

**Comment by Dionakra** [comment]
Buenas Andrés.

Estas cositas han sido subsanadas en otras issues, por lo que cierro esta. ¡Gracias por la aportación!
