### ISSUE TITLE
Frontend: Registro de Compañías - Arreglos varios

### ISSUE THREAD

**Issue by Dionakra** [Metronus/metronus#10]
En el registro de compañías existen algunos problemas actualmente, a saber:

- [x] La internacionalización no funciona correctamente. Con la aplicación en español o inglés los nombres de los campos aparecen indistintamente en inglés. Además aparecen los nombres directos de la Base de Datos, no nombres que se puedan mostrar al usuario.
![image](https://cloud.githubusercontent.com/assets/9566078/23834105/01edc7b2-0751-11e7-8ce2-220efdf7dc8d.png)

- [x] Los errores mostrados aparecen también en inglés y en un formato nada visual, con el código del mensaje. Se debería personalizar para el usuario.
![image](https://cloud.githubusercontent.com/assets/9566078/23834104/fa506a78-0750-11e7-83ba-e582074ff6b1.png)

- [x] El botón que diferencia entre la información de la compañía y el administrador lleva a confusión. Cuando se muestra la información de la compañía el botón muestra "company_info", ¿Por qué alguien pulsaría ahí? Propongo una modificación en el que aparezca este procedimiento por pasos, siendo el paso 1 el registro de la compañía y el 2 el del administrador, haciendo que se diferencien claramente ambos pasos.
- [x] La selección de logo con el botón por defecto de selección de imágenes se me antoja una implementación algo "lazy", mejorar para que se vea algo más personalizado y en consonancia con el resto.
![image](https://cloud.githubusercontent.com/assets/9566078/23834116/2c1b5b12-0751-11e7-952b-387e12236e00.png)

- [x] Al seleccionar un logo te permite seleccionar cualquier tipo de fichero. Deben permitirse únicamente PNG y JPEG
![image](https://cloud.githubusercontent.com/assets/9566078/23834119/47af1e7c-0751-11e7-9175-c987409f74b2.png)

- [x] Al introducir una contraseña empieza a aparecer como correcta con una sola letra. Deberíamos poner unos mínimos para las contraseñas.
![image](https://cloud.githubusercontent.com/assets/9566078/23834125/6ae1a59a-0751-11e7-89ff-0498d1718bc3.png)

- [x] Al repetir las contraseñas, aunque no coincidan, las marca como correctas.
![image](https://cloud.githubusercontent.com/assets/9566078/23834128/7aa3017c-0751-11e7-8a57-aa8d07aab037.png)

- [ ] Al pulsar en register con datos erróneos, como la contraseña mal en la anterior imagen, me ha eliminado todos los datos y me ha dejado en la misma vista, sin ningún tipo de mensaje de qué ha pasado

**Comment by jcliebanafdz** [comment]
Paso a comentar los diferentes puntos mencionados:

Puntos 1 y 2:
El problema de la internacionalización surge del cambio realizado por los compañeros. A día de hoy creo que todos los integrantes de front-end tenemos el mismo problema, por lo que será algo a tratar en breves, pero no es considerado un error de la plantilla de registro.
Punto 3:
Se trató de realizar un registro progresivo en pasos, como se propone, sin embargo, reconsideré dicha idea y me pareció más correcto dar la opción de modificar cualquier dato en cualquier momento, pudiendo alternar la vista entre la información de la compañía y la información del administrador.
En la última versión, el mensaje que se muestra es más intuitivo, además de el hecho de que no es posible pulsar sobre el botón "registro", lo cual creo que es bastante buena razón para pulsar el otro botón.

Punto 4 y 5:
Completamente de acuerdo. Se modificará en el futuro.

Punto 6:
De ser así, necesito conocer los requerimientos mínimos de las contraseñas, o que se me indique que queda a mi elección.

Punto 7:
Corregido en la última versión.

Punto 8:
Soy conocedor de este problema. Se tratará de corregir en el futuro.

**Comment by Dionakra** [comment]
Subo esta Issue para recordar que aún está pendiente. Como veo que has estado tocando cosas del registro, dejo en tus manos su pleno funcionamiento.
