### ISSUE TITLE
Frontend: Autenticación de usuarios

### ISSUE THREAD

**Issue by Dionakra** [Metronus/metronus#11]
En la autenticación de usuarios existen varios problemas actualmente, a saber:

- [x] En la internacionalización, se mezclan mensajes en inglés y español. El botón de Iniciar Sesión no cambia nunca.
![image](https://cloud.githubusercontent.com/assets/9566078/23834163/0c1eb678-0752-11e7-8ff5-87b1aa20fa9d.png)

- [x] No se controla que esté vacío el formulario para enviarlo. Permite enviar una petición al servidor con alguno de los campos vacíos.
![image](https://cloud.githubusercontent.com/assets/9566078/23834174/3762822e-0752-11e7-9be5-59bd26ee9bf5.png)

- [x] Al enviar el formulario, en caso de que no sea exitoso no aparece ni un solo mensaje de por qué no te has podido loguear.

- [x] Los mensajes de error no están tratados correctamente, mostrando los textos de forma burda y poco estilística. 

- [x] La página que aparece tras el login exitoso no muestra ningún tipo de personalización. No sabemos con quién nos acabamos de loguear.

**Comment by jcliebanafdz** [comment]
La página de login actual es algo temporal hasta que se completara la de registro.

Se trabajaran sobre todos esos puntos a partir de ahora.

**Comment by josgavrui1** [comment]
Además de lo que te ha dicho David, hay otro error (que ya dije en su momento, pero lo expongo para que no se olvide) que hace que en móvil la contraseña no se muestre como debería, sino que se muestra el texto. Adjunto ejemplo: 
![screenshot_20170314-143628](https://cloud.githubusercontent.com/assets/22834907/23903339/7c16789e-08c4-11e7-9f54-fd961b481d7c.png)

Edit: En el pc también me ha pasado, se ve que pasa a veces sí y a veces no...

**Comment by jcliebanafdz** [comment]
Actualmente, aunque si se muestra mensaje si el usuario no existe o ha habido algún error, esta en un formato no definitivo. (mu feo, vaya)

**Comment by Dionakra** [comment]
Corregido todo en la nueva interfaz. ¡Gracias!
