### ISSUE TITLE
Frontend: Gestión de Departamentos

### ISSUE THREAD

**Issue by Dionakra** [Metronus/metronus#12]
Las vistas de creación, edición, lista y borrado de departamentos tienen algunos problemas, a saber:

- [x] La internacionalización no funciona. Teniendo la página en español, los mensajes aparecen en inglés indistintamente.
![image](https://cloud.githubusercontent.com/assets/9566078/23834200/af7b15fa-0752-11e7-9270-acf8e7ed078a.png)
![image](https://cloud.githubusercontent.com/assets/9566078/23834216/fa90fdac-0752-11e7-9885-b202e4f1ddb5.png)

- [x] Los títulos son pobres. createDepartment o listDepartment no deberían aparecer. Algo más claro sería lo mejor como "Creación de Departamentos", algo que sea obvio.
![image](https://cloud.githubusercontent.com/assets/9566078/23834221/10da1fd0-0753-11e7-881a-c6c5a692f4a9.png)

- [x] Al crear un departamento con el nombre de un departamento existente no devuelve ningún tipo de mensaje.
- [x] Actualmente al crear un departamento devuelve a la lista. Debería ofrecer dos opciones
- Crear y continuar, que se cree de forma asíncrona, informe con un mensaje de éxito / error, en caso de éxito borrar el formulario y dejarlo en la misma pantalla, en caso de error mostrar por qué falla.
- Crear. Cuando se cree el departamento y sea exitoso, enviar a una lista de detalles de ese departamento.

- [x] En la edición de departamentos ocurre exactamente lo mismo que al crearlos con la duplicidad de nombres. No te permite modificarlo a un departamento existente, pero no te dice qué pasa, simplemente te deja en el mismo sitio.

- [x] Al borrar un departamento, te lo permite y no te pide ningún tipo de comprobación. Personalmente añadiría un modal donde se expliquen las consecuencias y que acepte. Hasta entonces no enviar la petición al servidor.

**Comment by anddonram** [comment]
ya esta el metodo asincrono para crear, asi como los mensajitos para avisar. visita departmentControllr.py para mas informacion

**Comment by josgavrui1** [comment]
Creo que ya están corregidos todos los puntos que se pedían. Existe un fallo (que no he conseguido resolver) que consiste en que si envías el formulario y falla (por ejemplo, si está el nombre repetido), la vista se muestra como si se estuviese editando en lugar de creando. He estado probando en el formulario de la creación de proyectos y ocurre exactamente lo mismo, por lo que igual @andjimrio es capaz de solucionarlo. Si falta algo más, avísame.

**Comment by Dionakra** [comment]
Por favor, marca del mensaje original los checks de lo que esté terminado, así veo qué puntos exactos tengo que revisar y cuales están pendientes.

Luego les echo un hojaldre.

**Comment by Dionakra** [comment]
Esto funciona maravillosamente, ¡muchas gracias compañeros!
