### ISSUE TITLE
Frontend: Gestión de Proyectos

### ISSUE THREAD

**Issue by Dionakra** [Metronus/metronus#13]
En las vistas de la Gestión de Proyectos tenemos algún que otro problema, a saber:

- [x] La internacionalización no funciona. Teniendo la página en español, los mensajes aparecen en inglés indistintamente.
![image](https://cloud.githubusercontent.com/assets/9566078/23834332/367670a2-0755-11e7-82f8-15f9cc00da33.png)

- [x] Los títulos son pobres. createProject no debería aparecer. Algo más claro sería lo mejor como "Creación de Proyectos", algo que sea obvio.
![image](https://cloud.githubusercontent.com/assets/9566078/23834335/46816416-0755-11e7-9809-988067e65ac4.png)

- [x] Al crear un departamento con el nombre de un departamento existente no devuelve ningún tipo de mensaje, de hecho cambia a modo "edición" por alguna razón que no comprendo. 
![image](https://i.gyazo.com/3a069949b3dc9ad95e93290367c09673.gif)

- [x] Actualmente al crear un proyectodevuelve a la lista. Debería ofrecer dos opciones
- Crear y continuar, que se cree de forma asíncrona, informe con un mensaje de éxito / error, en caso de éxito borrar el formulario y dejarlo en la misma pantalla, en caso de error mostrar por qué falla.
- Crear. Cuando se cree el proyecto y sea exitoso, enviar a una lista de detalles de ese departamento.

- [x] En la edición de proyecto ocurre exactamente lo mismo que al crearlos con la duplicidad de nombres. No te permite modificarlo a un proyecto existente, pero no te dice qué pasa, simplemente te deja en el mismo sitio.

- [x] Al borrar un proyecto, te lo permite y no te pide ningún tipo de comprobación. Personalmente añadiría un modal donde se expliquen las consecuencias y que acepte. Hasta entonces no enviar la petición al servidor.

**Comment by andjimrio** [comment]
David, lo del idioma es cosa del encargado de Heroku, que haga algo así:
heroku run python manage.py compilemessages

Porque en local funciona.
Lo demás, me pongo manos a la obra.
PD: meto a Álvaro en la incidencia porque me ayudará con el back-end de esta parte.

**Comment by Dionakra** [comment]
Sí, eso hemos estado comentando con @josgavrui1 , voy a abrir una Issue para el que controla esto en Heroku, que no es otro que @raisans138

**Comment by andjimrio** [comment]
Para el que me falta, necesito tu ayuda @Guardsoul 

Crear y continuar, que se cree de forma asíncrona, informe con un mensaje de éxito / error, en caso de éxito borrar el formulario y dejarlo en la misma pantalla, en caso de error mostrar por qué falla.
- Aquí pues con un botón submit con datos propios. Es decir, que cuando el submit envíe tal cosa, te devuelva a la página de inicio.

Crear. Cuando se cree el proyecto y sea exitoso, enviar a una lista de detalles de ese departamento.
- Aquí hacer que lo haga en el servidor.

Espero tus respuestas.

PD: @Dionakra yo prefiero hacer AJAX al final, si no te importa y centrarme luego en el diseño y en la funcionalidad. Sobre todo, para hacerlo con Vue y todos de manera homogénea.

**Comment by andjimrio** [comment]
Por mi parte, está hecho: falta revisarlo por @Dionakra 👍 
-> Estimado: 4
-> Hecho: 7

**Comment by Dionakra** [comment]
La eliminación de proyectos no me hace nada. Pls, revisen. Gracias

**Comment by renato-rg** [comment]
Arreglado en 8bd9380dbf9eb5cae0bef433720c1d83125e9204
