### ISSUE TITLE
Heroku: Compilación de mensajes de frontend

### ISSUE THREAD

**Issue by Dionakra** [Metronus/metronus#15]
Actualmente parece que existe un problema con Heroku, que no está compilando los mensajes y, por ello, la internacionalización no está funcionando correctamente. Por favor @raisans138 , échale un vistazo a ver si se puede forzar a que haga esto en Heroku.

Existen varias posibles soluciones por internet, por favor, échale un rato cuando puedas.

https://github.com/heroku/heroku-buildpack-python/issues/198

**Comment by josjimjim** [comment]
Ya he solucionado el problema con la internacionalización en Heroku. Se ha añadido el fichero de configuración ["post_compile"](https://github.com/Metronus/metronus/blob/dev/bin/post_compile) que resuelve este error. 

Encontré la solución en los siguientes enlaces
https://devhub.io/repos/nigma-heroku-django-cookbook
https://github.com/okfde/froide/blob/4cf78328939ce2387304085a402f130c5cf5c5f0/bin/post_compile#L13-L47
https://github.com/piotras/heroku-buildpack-gettext

**Comment by Dionakra** [comment]
He estado probando algunas vistas y parece que ya funciona la internacionalización en todas las vistas.

Muchas gracias @raisans138 , cierro.
