### ISSUE TITLE
Error en creación de departamentos

### ISSUE THREAD

**Issue by Guardsoul** [Metronus/metronus#2]
A la hora de crear un departamento una vez introducido el nombre y pulsado enviar se cambia el título de la página a "Edit department" pero el departamento no se ha creado ni se muestra en la lista.

**Comment by josgavrui1** [comment]
https://github.com/Metronus/metronus/issues/12
Es el único error que me queda por solucionar del formulario, estoy a la espera de ver si Andrés tiene alguna solución mejor a la que se me ha ocurrido, ya que tiene el mismo problema que yo con su formulario de los proyectos.

PD: La próxima vez, por favor, asígname a la issue para que me entere más rápido, si no, es posible que se me pase.

**Comment by Dionakra** [comment]
Esta issue ya estás solucionada, vamos chapando...
