### ISSUE TITLE
Backend: Gestión de pagos con PayPal

### ISSUE THREAD

**Issue by Dionakra** [Metronus/metronus#21]
En este Sprint introduciremos la opción de pagar para aquellos usuarios que lo necesiten. Por favor, id investigando qué tal funciona esto en Django.

**Comment by Dionakra** [comment]
Quedamos que con la librería no funcionaba, ¿Se ha probado a hacer los pagos variables por mes?

**Comment by j4rv** [comment]
Para hacer pagos periódicos con coste variables hay que cumplir el estándar PCI compliance https://www.paypal.com/uk/webapps/mpp/pci, porque tendríamos que guardar las tarjetas de crédito de los clientes. 

Sin el estándar paypal no lo permite, y con el estándar se haría con Paypal Payments Pro.

Cierro la issue?
