### ISSUE TITLE
Frontend: Métricas de un proyecto

### ISSUE THREAD

**Issue by Dionakra** [Metronus/metronus#25]
En este segundo sprint vamos a añadir información extra para los proyectos, a saber:

- [x] Número de empleados asociados por departamento del proyecto. Debe mostrarse en un gráfico circular que, al poner el ratón encima, se vea un detalle (nombre del departamento y número de empleados, por ejemplo). Al pinchar en una sección, debe llevar al detalle de ese departamento.
- [x] Número de tareas por departamento del proyecto. Exactamente igual que lo anterior pero con tareas.
- [x] Número de horas por departamento del proyecto, donde se podrá filtrar por intervalo temporal, siendo el intervalo por defecto el mes actual. Aquí debe mostrarse un gráfico de barras donde se explicite la media de horas trabajadas de los departamentos. Algo así debería quedar:

![image](https://cloud.githubusercontent.com/assets/9566078/24453517/8468cafe-1488-11e7-9921-49752d181171.png)

**Comment by jcliebanafdz** [comment]
Lo de hacer click de momento no esta. 
No lo considero prioritario ahora mismo como para retrasar el resto de tareas debido a ello.

**Comment by jcliebanafdz** [comment]
@agubelu @Dionakra 
Existe un pequeño inconveniente con la última gráfica.
En el controlador, por defecto, si no hay horas imputadas para un departamento, se settean a 0.
El problema viene en que el controlador devuelve TODOS los departamentos, sean del proyecto o no, y al ser posible la existencia de departamentos con 0 horas imputadas, no puedo filtrar aquellos departamentos que no son del proyecto.

Si se filtran comprobando el valor de 'value', se filtrarán igualmente aquellos departamentos del proyecto en los que aun no haya horas asignadas, por lo que no se mostrarían, mostrándose una información no del todo completa.

**Comment by jcliebanafdz** [comment]
@agubelu 
Hay una petada curiosa cuando se crea un proyecto sin tener empleados aun registrados.

![image](https://cloud.githubusercontent.com/assets/6805982/25063188/e6a84138-21dd-11e7-9c70-15b8ce68cf03.png)

**Comment by agubelu** [comment]
Has hecho migraciones y toda la pesca? Falta una columna en la BD
