### ISSUE TITLE
Frontend: Productividad de una tarea

### ISSUE THREAD

**Issue by Dionakra** [Metronus/metronus#29]
Para este segundo sprint vamos a introducir las productividades de las tareas, para ello, en la vista del detalle de una tarea se debe mostrar:

Productividad de la tarea por días en un intervalo de tiempo dado (por defecto el mes actual). Para esto simplemente se suman las horas de trabajo para cada día, se obtiene cuanto se produce por hora para ese día y se compara con cuantas unidades se deberían haber producido para ese día en base a las horas.

El resultado debe quedar algo así:
![image](https://cloud.githubusercontent.com/assets/9566078/24608286/355576dc-1876-11e7-89e2-43d51c1fe7ac.png)

**Comment by andjimrio** [comment]
Donde imputo las horas de esto?

**Comment by andjimrio** [comment]
Esta gráfica, David, son de las del tema, o de otra librería?

**Comment by andjimrio** [comment]
Tiempos:
03/04: 2h 15m
04/04: 3h

**Comment by anddonram** [comment]
hay alguna manera de q se pongan solo los dos primeros decimales? porque en las de empleado salen chorricientos...

**Comment by Dionakra** [comment]
Entiendo que con un round o un truncate a 2 no? En back o en front, lo mismo da.

**Comment by andjimrio** [comment]
Creo que está listo. Ciérralo cuando quieras @Dionakra
