### ISSUE TITLE
Backend: Gestión de Tareas

### ISSUE THREAD

**Issue by Dionakra** [Metronus/metronus#3]
Necesitamos gestionar las tareas de una empresa en la aplicación, donde necesitaremos los siguientes datos para cada tarea:

- Nombre de la Tarea
- Fecha de Creación
- ¿Activa?
- Creado por

Asimismo, necesitaremos realizar las siguientes operaciones con las tareas

### Creación de Tareas.
Un Administrador, Gerente, Jefe de Proyecto o Coordinador deben poder crear tareas. Las tareas estarán enlazadas a un proyecto y departamento, por lo que una tarea concreta solo pertenece a una dupla de estas. Como es obvio, un Jefe de Proyecto sólo podrá crear tareas en los proyectos en los que esté adscrito, así como sus departamentos. Mismo caso para el Coordinador de un departamento. Un Jefe de Proyecto que lo sea del proyecto A pero no del B no podrá crear una tarea allí. El Gerente y el Administrador puede crear tareas allá donde quiera. El nombre de la tarea no podrá repetirse dentro del mismo Proyecto y Departamento.

### Edición de Tareas.
Teniendo las mismas restricciones que en la edición de tareas, es decir, tanto de permisos de creación, de duplicidad de nombres y demás, las tareas deben poder editarse, únicamente el Nombre de la Tarea.

### Eliminación de Tareas
Con las mismas restricciones de antes, deben poder eliminarse las tareas, pero como sabemos, no se eliminarán como tal, dado que se perdería mucha información referenciada, se pondrá como inactiva. Sólo en el caso de que la tarea no tenga asociada aún ninguna imputación de horas podrá eliminarse "de verdad". Mientras tanto, sólo se desactiva.

**Comment by anddonram** [comment]
como preferís crear las tareas, viendo una lista de tareas por departamento y proyecto? o en el formulario, un desplegable donde escojas el departamento y el proyecto?
 en la primera, la url sería así como task/create/proyecto2/department4, eso quedaría feo en mi opinion, deberia ir en el formulario
con lo otro, cabe la posibilidad de que el desplegable sea muy largo, pero creo que es la mejor solucion.

**Comment by anddonram** [comment]
También estoy pensando si necesitaremos guardar al que creó la tarea, creo que no porque cualquiera con los roles adecuados puede modificarla.

**Comment by anddonram** [comment]
Me ha surgido un problema. El contexto es el siguiente:
-Un administrador tiene que poder crear tareas donde quiera
-ProjectDepartmentEmployeeRole hace referencia a empleado y su rol, que puede ser "Administrator"
-Ahora mismo solo pueden crear tareas los empleados con ese rol, no los Administradores en si como actores
-No tiene mucho sentido un empleado Administrador asignado a un solo departamento y proyecto, para eso están los otros roles. Por tanto, debería desaparecer ese tipo de rol, y que sea el Administrator el que pueda crear donde quiera
