### ISSUE TITLE
Backend: Productividad de un trabajador

### ISSUE THREAD

**Issue by Dionakra** [Metronus/metronus#30]
En este sprint veremos como de productivo es un trabajador. Para ello debemos añadir en el perfil de ese trabajador un apartado donde se puedan ver, por cada tarea, la productividad que ha tenido en cada día que ha trabajado, además de un acumulado de productividad. Es decir, deben mostrarse dos apartados como mínimo:

- [x] Un apartado donde por cada tarea en el intervalo seleccionado aparezca la productividad por día, comparado a la supuesta productividad que tendría que tener.
- [x] Un apartado donde aparezca el acumulado de la productividad por cada tarea, junto al que debería tener

**Comment by anddonram** [comment]
falta que se pueda escoger las fechas en front para que se envie por la url.
y ponerlo bonito, que la total y la esperada las he puesto asi rapido y feo
(y tests)
