### ISSUE TITLE
Frontend: Sección de contacto en landing page

### ISSUE THREAD

**Issue by jcliebanafdz** [Metronus/metronus#32]
Al ser requerido un form para enviar los datos de contacto a backend y procesarlos, actualmente hay que variar la forma en la que esta hecha la landing page.
No es algo sumamente complejo, pero actualmente prefiero dedicar el tiempo a otras tareas.

Abro la issue únicamente para que no se me olvide hacerlo.

**Comment by Dionakra** [comment]
Ya está hacido, perfecto
