### ISSUE TITLE
Frontend: No se permite añadir más de un rol a un actor

### ISSUE THREAD

**Issue by jcliebanafdz** [Metronus/metronus#33]
Actualmente sucede que, tras añadir un rol a un actor, no es posible añadir ninguno más, alegando la página que ese rol ya ha sido añadido.

**Comment by jcliebanafdz** [comment]
Te añado a ti @Dionakra porque no se quien fue el encargado de esta parte.

**Comment by Dionakra** [comment]
No se pueden añadir varios roles a un actor en el mismo departamento y proyecto, pero con otro departamento y proyecto, sí. No tiene sentido ser empleado y coordinador para una misma dupla Proyecto-Departamento, y es obvio y está correcto.

Respecto al poder añadir más de un rol sí que se puede pero, de nuevo, en diferentes proyectos y departamentos:

![image](https://cloud.githubusercontent.com/assets/9566078/25045329/055a2860-212c-11e7-942a-f3cc8a5d310e.png)


Eso está correcto.

**Comment by jcliebanafdz** [comment]
Okey. Culpa mia pues. Aun asi, estaría bien cambiar en un futuro el mensaje de error.
