### ISSUE TITLE
Frontend: Gestión de Tareas

### ISSUE THREAD

**Issue by Dionakra** [Metronus/metronus#4]
Necesitamos gestionar las tareas de una compañía, para ello necesitamos una vista que gestione estos elementos, para ello necesitamos:

### Listado de Tareas por Proyecto y Departamento
En la vista de detalles de un proyecto y departamento debe aparecer un apartado donde se puedan observar las tareas que cuelgan de este estamento. Ésto solo lo podrán hacer los Administradores, Gerentes, Jefes de Proyecto (para su proyecto) y Coordinadores (para su departamento). Además deberá poder ofrecerse la posibilidad de crear nuevas tareas, editarlas o borrarlas

### Vista de detalles de la tarea
Una vista donde se vean las propiedades de una tarea, que de momento son:
- Nombre de la Tarea
- Proyecto
- Departamento
- Fecha de Creación
- Creador

### Creación de Tareas
Debe ofrecerse una vista para la creación de Tareas. Debe elegirse de forma obligatoria un Proyecto y Departamento donde asociarse ésta nueva tarea. Sólo deberá informarse el nombre de la tarea. En caso de duplicidad de nombre de tarea para ese proyecto y tarea, avisar al usuario.

La carga de los departamentos adscritos a un proyecto después de seleccionarlo debe ser asíncrono para evitar una recarga de la interfaz a cada selección. Dar dos opciones:
Crear tarea y continuar. Se informa de que la inserción ha ido bien, se limpia el formulario y se inicia nueva inserción
Crear tarea. Se redirige a la vista de detalles de la tarea

### Edición de Tareas
Debe poder editarse una tarea, únicamente el nombre. Cuando todo vaya OK, enviarlo a la vista de detalles de la tarea.

### Eliminación de Tareas
Debe poder eliminarse una tarea. Se informará de la gravedad de la acción al usuario. En caso de que así ocurra, confirmar la acción con backend. Al tener éxito, enviar al usuario a una vista de resumen de proyecto / departamento.

**Comment by anddonram** [comment]
el formulario de task no tiene botones para aceptar, tampoco tienen los desplegables para elegir el departamento y el proyecto

**Comment by Dionakra** [comment]
Los desplegables están añadidos, pero no están bien colocados y no refrescan la información del departamento con el proyecto seleccionado.

![image](https://cloud.githubusercontent.com/assets/9566078/24193543/e82a6fde-0ef2-11e7-983c-6d755264a57f.png)

**Comment by Dionakra** [comment]
Todo correcto
