### ISSUE TITLE
Backend: Imputación de Horas

### ISSUE THREAD

**Issue by Dionakra** [Metronus/metronus#5]
La aplicación basa su funcionalidad en la imputación de horas, por ello necesitamos dar pie a esta funcionalidad. Para la imputación de horas necesitamos lo siguiente
- Empleado
- Tarea
- Minutos 
- Fecha de Imputación
- Fecha de Trabajo
- Comentario sobre la imputación

Necesitamos realizar lo siguiente con las horas:

### Creación de Imputación de horas
Cualquier empleado debe poder imputar horas en una tarea de las que tenga acceso. Es decir, si un empleado lo es en el departamento A del proyecto Z, que pueda imputar horas ahí, pero si no trabaja en el departamento B, que no pueda imputar horas en ese departamento. Además aplican las siguientes restricciones
- El empleado debe estar activo en el momento de la imputación
- La tarea debe estar activa en el momento de la imputación
- Los minutos deben ser positivos, y el total de la imputación de ese día no puede superar las 24 horas
- La Fecha de la Imputación debe ser introducida automáticamente
- La Fecha de Trabajo tiene que ser la actual o pasada, no podrá imputarse a futuro.

### Edición de Imputación de horas
El empleado debe poder editar sus horas, únicamente si las modifica el mismo día que ha imputado. En otro caso se bloquearan para el empleado. Las restricciones son las mismas que en la creación.

### Eliminación de Imputación de horas
Al igual que la edición, sólo se podrán borrar las imputaciones el mismo día. Pasado ese día, se bloquean

**Comment by Guardsoul** [comment]
Métodos creados. En cuanto @andjimrio termine con la parte de frontend y le dé el visto bueno pasamos a los tests.

**Comment by andjimrio** [comment]
@Guardsoul falta hacer el list_all: que muestre ne una cuadrícula todas las tareas del hippy y pueda rellenarlas ahí
