### ISSUE TITLE
Frontend: Imputación de Horas

### ISSUE THREAD

**Issue by Dionakra** [Metronus/metronus#6]
La aplicación debe ofrecer vistas para poder gestionar las horas trabajadas. Para ello debemos mostrar lo siguiente.

### Creación de Horas
La aplicación debe mostrar una interfaz donde al trabajador se le ofrezca un resumen de las horas del mes actual, en un grid, donde las columnas serán los días del mes, y las filas las tareas, donde se pondrán las horas trabajadas en cada tarea / día. Al final de la columna debe ofrecerse un total de horas trabajadas en ese día. Además, debe ofrecerse un detalle de las horas totales trabajadas en ese día. 

Debajo de ese cuadro deben aparecer varios campos a elegir, a saber:
Proyecto
Departamento
Comentario de las horas
Horas y Minutos

Donde el Departamento cargará asíncronamente al elegir un proyecto, el comentario de las horas no será necesario, pero sí lo serán las horas y minutos, donde no podrán ser mayor a 24 horas por razones obvias.

El usuario debe poder guardar la imputación y, en caso de que todo vaya bien, asíncronamente limpiar el formulario y actualizar el cuadro de resumen.

### Edición de Horas
En el cuadro resumen dar la opción a las horas imputadas en el día actual que se puedan editar. Ofrecer un cuadro sobreimpresionado donde se pueda eliminar o cambiar las horas imputadas. La actualización, de nuevo, debe ser asíncrona.

**Comment by andjimrio** [comment]
Hecho de manera más sencilla (paso a paso) para luego hacer lo de la tabla. Pero @Dionakra ... me dicen que eso, lo de la tabla con todas las tablas de un empleado lo tiene que hacer el encargado de la interfaz de empleados.
Lo hago yo y es tarea de otro?

**Comment by Dionakra** [comment]
No he entendido demasiado, pero luego os reviso las issues y os hago un par de comentarios, please be excited

**Comment by andjimrio** [comment]
Faltan retoques de diseño... 

Previsto: 5
Real: 7

**Comment by andjimrio** [comment]
Creo que ya está. Dime, qué tal y la cierro
