### ISSUE TITLE
Backend: Métricas de uso de la aplicación

### ISSUE THREAD

**Issue by Dionakra** [Metronus/metronus#8]
Necesitamos funcionalidades para la parte de administración más allá de la operativa de la herramienta. Por ello, si es posible, que alguien investigue cómo podríamos mostrar los empleados conectados actualmente a nuestra empresa, y estudiar diferentes métricas, como tareas por departamento / proyecto / compañía, empleados por tareas y demás.

**Comment by anddonram** [comment]
Voy a echar un vistazo a estas cosas. En primer lugar haré unas cuantas queries.
Lo que he leido es que Django no tiene un registro de usuarios logeados en el momento, pero se puede hacer mas o menos con workarounds (alias chanchullos )

**Comment by Dionakra** [comment]
Ya se han hecho algunas, usaremos Grafana (https://grafana.com/) para monitorear muchas cosas, y luego meteremos más métricas propias.
