### ISSUE TITLE
Backend: Formulario de creación/edición de roles de un empleado

### ISSUE THREAD

**Issue by josgavrui1** [Metronus/metronus#9]
A priori la lista de roles debería funcionar utilizando la navegación, sin embargo, aún no puedo probarlo porque no hay objetos. El formulario de creación/edición de roles de un empleado constará de lo siguiente: 
- Un desplegable con los departamentos de la compañía (en el caso de que se esté editando uno ya existente debería estar relleno con su valor actual).
- Un desplegable con los proyectos de la compañía (ídem que el departamento).
- Un desplegable con los roles (ídem).
- El empleado al que le estamos añadiendo/editando el rol en un campo oculto (supongo que te hará falta para saber de quién es el rol en el caso de creación).
Si crees que hace falta algo más avísame, por mi parte creo que eso es todo.

**Comment by agubelu** [comment]
Ya debería estar terminado, le he pasado una buena batería de tests pero si queda algo por corregir me avisas por aquí.

**Comment by Dionakra** [comment]
Estupendo, funciona fantásticamente, enhorabuena!
